default:
	cd makeprocs; make
	cd hello_world; make
	cd Step2.1; make
	cd Step2.2; make
	cd Step2.3; make
	cd Step2.4; make
	cd Step2.5; make
	cd Step2.6; make

clean:
	cd makeprocs; make clean
	cd hello_world; make clean
	cd Step2.1; make clean
	cd Step2.2; make clean
	cd Step2.3; make clean
	cd Step2.4; make clean
	cd Step2.5; make clean
	cd Step2.6; make clean

run0:
	cd ../../bin; dlxsim -x os.dlx.obj -a -u makeprocs.dlx.obj 0; ee469_fixterminal

run1:
	cd ../../bin; dlxsim -x os.dlx.obj -a -u makeprocs.dlx.obj 1; ee469_fixterminal

run2:
	cd ../../bin; dlxsim -x os.dlx.obj -a -u makeprocs.dlx.obj 2; ee469_fixterminal

run3:
	cd ../../bin; dlxsim -x os.dlx.obj -a -u makeprocs.dlx.obj 3; ee469_fixterminal

run4:
	cd ../../bin; dlxsim -x os.dlx.obj -a -u makeprocs.dlx.obj 4; ee469_fixterminal

run5:
	cd ../../bin; dlxsim -x os.dlx.obj -a -u makeprocs.dlx.obj 5; ee469_fixterminal

run6:
	cd ../../bin; dlxsim -x os.dlx.obj -a -u makeprocs.dlx.obj 6; ee469_fixterminal